import LpNavbar from "@/components/Navbar/LpNavbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full min-h-screen">
          <div className="max-w-[1440px] min-h-screen mx-auto px-4 sm:px-6 md:px-8 lg:px-4 bg-black">
            <LpNavbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
